[project]
name = "aula"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=24.10.0",
    "imageio>=2.37.0",
    "manim>=0.19.0",
    "matplotlib>=3.10.0",
    "python-lsp-server>=1.12.0",
]
